# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jevon's Personal Pages
email: my_email_is_not@all-hard-to.find
description: > # this means to ignore newlines until "baseurl:"
  Jevon Longdell's webpages for personal stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jevonlongdell.github.io" # the base hostname & protocol for your site
github_username:  jevonlongdell

# Build settings
markdown: kramdown
